### ISSUE TITLE
Fix codice identificativo e fonti dei requisiti (capitolo 2.2.4.3)

### ISSUE THREAD

**Issue by MatthewBalzan** [Omicron-Team/Documentazione#36]
Fonti:
- Capitolato
- Interno: "Requisito individuato dagli analisti e ritenuto opportuno"
- Caso d'uso
- Verbale (scrivendo che viene riportato il codice del verbale)

Importanza:
- Usare numeri invece che lettere (1,2,3 in ordine di importanza, più facile da leggere)

**Comment by nicomanto** [comment]
![image](https://user-images.githubusercontent.com/72399987/103439362-85b65580-4c3c-11eb-86fd-465181a2785c.png)


Può andare bene come correzione?

**Comment by MatthewBalzan** [comment]
1 - Obbligatorio
2 - Desiderabile
3 - Facoltativo

I verbali puoi metterli insieme, tanto mettiamo il codice
