### ISSUE TITLE
Fix numerazione casi d'uso

### ISSUE THREAD

**Issue by nicomanto** [Omicron-Team/Documentazione#89]
"numerazione dei casi d’uso non è abbastanza chiara (ad esempio, UC3.2.3 e suoi sotto-casi d’uso)"

**Forse da fixare anche nelle norme di progetto?**

**Comment by desoul99** [comment]
Ho provato a semplificare UC3, rimuovendo i due casi d'uso critici. Secondo me è da valutare se separare completamente in pagine distinte il login cliente e merchant, in modo da risolvere in parte anche #88.
